Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Standard python numerical analysis imports:
import numpy as np
from scipy import signal
from scipy.interpolate import interp1d
from scipy.signal import butter, filtfilt, iirdesign, zpk2tf, freqz
import h5py
import json

# the IPython magic below must be commented out in the .py file, since it doesn't work there.
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab

# LIGO-specific readligo.py 
from ligotools import readligo as rl
# utility functions
from ligotools.utils import whiten, write_wavfile, reqshift, create_plot

# you might get a matplotlib warning here; you can ignore it.
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/cc/_v11yjcd1ws350v6ddxmf2lc0000gp/T/ipykernel_15089/3656950652.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;32mfrom[0m [0mligotools[0m [0;32mimport[0m [0mreadligo[0m [0;32mas[0m [0mrl[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m [0;31m# utility functions[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m [0;32mfrom[0m [0mligotools[0m[0;34m.[0m[0mutils[0m [0;32mimport[0m [0mwhiten[0m[0;34m,[0m [0mwrite_wavfile[0m[0;34m,[0m [0mreqshift[0m[0;34m,[0m [0mcreate_plot[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     19[0m [0;34m[0m[0m
[1;32m     20[0m [0;31m# you might get a matplotlib warning here; you can ignore it.[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Downloads/hw06-luzgool-main/ligotools/utils.py[0m in [0;36m<module>[0;34m[0m
[1;32m     12[0m [0mmyPath[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mdirname[0m[0;34m([0m[0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mabspath[0m[0;34m([0m[0m__file__[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m [0msys[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0minsert[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0mmyPath[0m [0;34m+[0m [0;34m'/../'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 14[0;31m [0;32mimport[0m [0mreadligo[0m [0;32mas[0m [0mrl[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     15[0m [0;34m[0m[0m
[1;32m     16[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'readligo'
ModuleNotFoundError: No module named 'readligo'

